name: 'Build'

on:
  pull_request:
  workflow_call:

env:
  GH_TOKEN: '${{ secrets.GH_TOKEN }}'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build package
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist

  Build_Storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build storybook
        run: npm run build-storybook

      - name: Upload build-storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-storybook-artifact
          path: storybook-static
